Repository chipsalliance/verible, pull requests merged in 2021-05, with the labels that each got.

#804 Make remaining test pass on Windows
  .github/workflows/windows-compile.yml
  verilog/tools/lint/verilog_style_lint.bzl
  verilog/tools/syntax/export_json_examples/verible_verilog_syntax_test.py
Labels: cla: yes

#807 Use `common` for platform-specific bazel configs:
  .bazelrc
Labels: cla: yes

#809 Avoid copy in range-for loop
  common/util/file_util.cc
Labels: cla: yes

#613 Align comments in port list
  common/formatting/align.cc
  common/formatting/align.h
  verilog/formatting/align.cc
  verilog/formatting/formatter_test.cc
Labels: cla: yes

#648 disable fork_label rule for linter
  verilog/CST/verilog_matchers.h
  verilog/analysis/checkers/BUILD
  verilog/analysis/checkers/disable_statement_rule.cc
  verilog/analysis/checkers/disable_statement_rule.h
  verilog/analysis/checkers/disable_statement_rule_test.cc
  verilog/analysis/default_rules.h
  verilog/tools/lint/BUILD
  verilog/tools/lint/testdata/disable_statement.sv
Labels: cla: yes

#802 Fix indentation on named arguments of functions
  verilog/formatting/formatter.cc
  verilog/formatting/formatter_test.cc
  verilog/formatting/tree_unwrapper.cc
Labels: cla: yes

#820 Use latest gflags, which does not produce a fallthrough-warning.
  .github/bin/build-and-test.sh
  WORKSPACE
Labels: cla: yes

#822 Fix missing break
  .github/bin/build-and-test.sh
  verilog/formatting/formatter.cc
Labels: cla: yes

#821 Enable warning about switch/case fallthrough.
  .github/bin/build-and-test.sh
Labels: cla: yes

#825 formatter: Fix crash caused by an alignment of null statement
  verilog/formatting/formatter_test.cc
  verilog/formatting/tree_unwrapper.cc
Labels: cla: yes

#668 Generate suggested-fixes for style-lint findings with trivial remedies
  common/analysis/BUILD
  common/analysis/lint_rule_status.cc
  common/analysis/lint_rule_status.h
  common/analysis/lint_rule_status_test.cc
  common/strings/BUILD
  common/strings/diff.cc
  common/strings/diff.h
  common/strings/diff_test.cc
  common/strings/patch.cc
  common/strings/split.cc
  common/strings/split.h
  common/strings/split_test.cc
  common/tools/BUILD
  common/tools/patch_tool.cc
  common/util/BUILD
  common/util/file_util.cc
  common/util/file_util.h
  common/util/user_interaction.cc
  common/util/user_interaction.h
  common/util/user_interaction_test.cc
  verilog/analysis/BUILD
  verilog/analysis/checkers/endif_comment_rule.cc
  verilog/analysis/checkers/forbid_consecutive_null_statements_rule.cc
  verilog/analysis/checkers/no_trailing_spaces_rule.cc
  verilog/analysis/checkers/posix_eof_rule.cc
  verilog/analysis/checkers/suggest_parentheses_rule.cc
  verilog/analysis/checkers/uvm_macro_semicolon_rule.cc
  verilog/analysis/verilog_linter.cc
  verilog/analysis/verilog_linter.h
  verilog/analysis/verilog_linter_test.cc
  verilog/tools/lint/BUILD
  verilog/tools/lint/README.md
  verilog/tools/lint/lint_tool_test.sh
  verilog/tools/lint/verilog_lint.cc
Labels: cla: yes

#827 Replaced build-version.sh with build-version.py
  .bazelrc
  bazel/build-version.py
  bazel/build-version.sh
  common/util/BUILD
  releasing/docker-run.sh
Labels: cla: yes

#832 Fix `workspace_status_command` on Windows
  .bazelrc
Labels: cla: yes

#816 Include tokens text in JSON output
  common/text/token_info_json.cc
  common/text/token_info_json.h
  common/text/token_info_json_test.cc
  verilog/CST/BUILD
  verilog/CST/verilog_tree_json.cc
  verilog/CST/verilog_tree_json_test.cc
  verilog/tools/syntax/BUILD
  verilog/tools/syntax/README.md
  verilog/tools/syntax/verilog_syntax.cc
Labels: cla: yes

#835 Fix README badge
  README.md
Labels: cla: yes, documentation

#837 formatter: Refinement of indentation for function arguments
  verilog/formatting/formatter.cc
  verilog/formatting/formatter_test.cc
  verilog/formatting/tree_unwrapper.cc
Labels: cla: yes, formatter

#819 Align parameters in exported/imported function
  verilog/CST/DPI.h
  verilog/CST/DPI_test.cc
  verilog/formatting/align.cc
  verilog/formatting/formatter_test.cc
  verilog/formatting/tree_unwrapper.cc
  verilog/formatting/tree_unwrapper_test.cc
  verilog/parser/verilog.y
Labels: cla: yes
